name: "Draft Release"

on:
  workflow_dispatch:

jobs:
  draft-release:
    uses: phorus-group/workflows/.github/workflows/draft-release.yml@main
    with:
      versioning: gradle
      slack-releases-channel: "C0AM8AEGJG7"
    secrets:
      slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
